<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WinHomestead.Native</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinHomestead.Core\WinHomestead.Core.csproj" />
  </ItemGroup>
</Project>
