<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WinHomestead.Tasks</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinHomestead.Core\WinHomestead.Core.csproj" />
  </ItemGroup>
</Project>
